### PR TITLE
API Documentation Swagger

### PR DESCRIPTION
**Pull request by daumie**
#### What does this PR do?
-  Introduce '**ESA**' API documentation using swagger
-  Aims to make product management a breeze- helps other internal teams know the details of  resources, methods, and their associated requests and responses, making maintenance and updates quicker.

#### Description of Task to be completed?
- Developers and other user alike will be able to integrate the ESA API as quickly as possible.

#### How should this be manually tested?
clone the repo
- `cd` into the project dir
- git-checkout to branch `ch-api-documentation-swagger`
- install application requirements with `npm install`
- use the information in `.env.sample` to provide the necessary environment variables i `.env`
- use `npm run start:dev` to start the application
- note that the default port is `8000`
- access sample swagger api documentation from the browser

> Since APIs are designed to be consumed, it is important to make sure that the client, or consumer, is able to quickly implement an API and understand what is happening with it. 

> Unfortunately, many APIs make implementation extremely difficult, defeating their very purpose. As we build out our API we want to ensure that we not only provide informational API documentation to help developers integrate/ debug connections, but also return back relevant data whenever a user makes a call—especially a call that fails.

> While having a well formatted, coherent body response in your API documentation is extremely important (we want something that can easily be deserialized, iterated and understood), we also want to provide developers with quick references as to what happened with the call, including the use of status codes. 

> And in the case of a failure, we will want to provide descriptive error messages that tell the client not just what went wrong, but how to fix it.

#### What are the relevant pivotal tracker stories?(if applicable)
 #160582419

### CODE REVIEW

**Comment by Kelechukwu** [comment]
Good job. I tested it and it works on my local. Just a few changes 
 **Update the READ.me with the following** 

- Details about the location of the YAML file. so that anyone would know where and how to add to the documentation 

- Details on the URL for the swagger  documentation . in your case its /api-docs

**Comment by IAMOTZ** [comment]
Job well done @daumie 
However, I noticed this on the user interface of the API documentation:
screen shot 2018-09-21 at 9 34 15 am
I am not sure if this application has anything to do with ***Authors Haven***, does it?

**Comment by daumie** [comment]
> Job well done @daumie
> However, I noticed this on the user interface of the API documentation:
> screen shot 2018-09-21 at 9 34 15 am
> I am not sure if this application has anything to do with _**Authors Haven**_, does it?

Hey @IAMOTZ , that must have been an oversight from my side. I will change it accordingly.

**Comment by daumie** [comment]
> Job well done @daumie
> However, I noticed this on the user interface of the API documentation:
> screen shot 2018-09-21 at 9 34 15 am
> I am not sure if this application has anything to do with _**Authors Haven**_, does it?

> This has been fixed.

**Pull request merged**
